# Generated by Django 4.2.30 on 2026-07-10 09:43

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroDeOrdens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('tipologia', models.CharField(max_length=30)),
                ('dividendos', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('taxa_de_cupao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_de_emissao', models.DateField(blank=True, null=True)),
                ('data_de_vencimento', models.DateField(blank=True, null=True)),
                ('ultima_cotacao', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('quantidade_de_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('preco_de_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('yield_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('quantidade_de_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('preco_de_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('yield_venda', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('data_referencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Livro de Ordens (tabela externa)',
                'verbose_name_plural': 'Livros de Ordens (tabela externa)',
                'db_table': 'livros_de_ordens',
                'ordering': ['codigo', 'data_referencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('mercado', models.CharField(max_length=50)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('variacao_percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('num_negocios', models.IntegerField()),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('data_referencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Resumo de Mercado (tabela externa)',
                'verbose_name_plural': 'Resumo de Mercado (tabela externa)',
                'db_table': 'resumo_mercados',
                'ordering': ['codigo', 'data_referencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('perfil', models.CharField(choices=[('INVESTIDOR', 'Investidor'), ('ADMINISTRADOR', 'Administrador')], default='INVESTIDOR', max_length=20)),
                ('tentativas_login_falhadas', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_pelo_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AtivoBodiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text="Corresponde ao 'codigo' em resumo_mercados/livros_de_ordens", max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ACAO', 'Ação'), ('OT', 'Obrigação do Tesouro'), ('BT', 'Bilhete do Tesouro')], max_length=20)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('taxa_juro_nominal', models.DecimalField(blank=True, decimal_places=4, help_text='Taxa de juro anual nominal (%)', max_digits=8, null=True)),
                ('data_maturidade', models.DateField(blank=True, null=True)),
                ('valor_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ativo BODIVA',
                'verbose_name_plural': 'Ativos BODIVA',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('preco_inicio', models.DecimalField(decimal_places=4, max_digits=20)),
                ('preco_fim', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rentabilidade_nominal_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('inflacao_acumulada_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rentabilidade_real_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_final_nominal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_final_real', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lucro_prejuizo_nominal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulacoes', to='bodiva_app.ativobodiva')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='bodiva_app.carteira')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADICAO', 'Adição de ativo'), ('REMOCAO', 'Remoção de ativo')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=20)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_simulada', models.DateField()),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodiva_app.ativobodiva')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='bodiva_app.carteira')),
            ],
            options={
                'verbose_name': 'Movimento de Carteira',
                'verbose_name_plural': 'Movimentos de Carteira',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_tentativa', models.CharField(blank=True, help_text='Email usado numa tentativa de login falhada, quando o utilizador não é identificável', max_length=255)),
                ('tipo', models.CharField(choices=[('LOGIN', 'Login bem-sucedido'), ('LOGIN_FALHADO', 'Tentativa de login falhada'), ('LOGOUT', 'Logout'), ('CRIAR_CARTEIRA', 'Criação de carteira'), ('ADICIONAR_ATIVO', 'Adição de ativo à carteira'), ('REMOVER_ATIVO', 'Remoção de ativo da carteira'), ('SIMULACAO', 'Simulação de investimento'), ('GERIR_UTILIZADOR', 'Gestão de utilizador'), ('GERIR_INFLACAO', 'Gestão de taxa de inflação'), ('GERIR_ATIVO', 'Gestão de ativo/dados financeiros'), ('CONSULTA_LOGS', 'Consulta de logs'), ('CONSULTA_DADOS_FINANCEIROS', 'Consulta de dados financeiros')], max_length=30)),
                ('detalhes', models.TextField(blank=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoInflacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('ipc_mensal', models.DecimalField(decimal_places=4, help_text='Variação percentual mensal do IPC (%)', max_digits=8)),
                ('fonte', models.CharField(default='INE Angola', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Histórico de Inflação',
                'verbose_name_plural': 'Histórico de Inflação',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PosicaoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preco_medio', models.DecimalField(decimal_places=4, help_text='Preço médio de aquisição (na data simulada)', max_digits=20)),
                ('data_simulada_compra', models.DateField(help_text='Data histórica usada como referência da compra')),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes', to='bodiva_app.ativobodiva')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='bodiva_app.carteira')),
            ],
            options={
                'verbose_name': 'Posição na Carteira',
                'verbose_name_plural': 'Posições na Carteira',
                'unique_together': {('carteira', 'ativo')},
            },
        ),
    ]
