# Generated by Django 4.2.30 on 2026-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bodiva_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='utilizadores_grupos', related_name='bodiva_user_set', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='utilizadores_permissoes', related_name='bodiva_user_permissions_set', to='auth.permission', verbose_name='permissões'),
        ),
        migrations.AlterModelTable(
            name='ativobodiva',
            table='ativos',
        ),
        migrations.AlterModelTable(
            name='carteira',
            table='carteiras',
        ),
        migrations.AlterModelTable(
            name='historicoinflacao',
            table='inflacao',
        ),
        migrations.AlterModelTable(
            name='logauditoria',
            table='logs',
        ),
        migrations.AlterModelTable(
            name='movimentocarteira',
            table='movimentos',
        ),
        migrations.AlterModelTable(
            name='posicaocarteira',
            table='posicoes',
        ),
        migrations.AlterModelTable(
            name='simulacao',
            table='simulacoes',
        ),
        migrations.AlterModelTable(
            name='user',
            table='utilizadores',
        ),
    ]